### ISSUE TITLE
Cut new release for LLVM 22 compat?

### ISSUE THREAD

**Issue by gonsoos** [greshake/i3status-rust#2250]
v0.35.0 fails to compile with LLVM 22.1.0 and `--no-default-features --features pipewire` possibly due to outdated dependencies:
```
   Compiling mailparse v0.14.1
     Running `/opt/rust-bin-1.93.1/bin/rustc --crate-name mailparse --edition=2018 /var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/cargo_home/gentoo/mailparse-0.14.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=f4ce1b39e5f2f6d7 -C extra-filename=-5288442ea7d1833d --out-dir /var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/i3status-rust-0.35.0/target/release/deps -C strip=debuginfo -L dependency=/var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/i3status-rust-0.35.0/target/release/deps --extern charset=/var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/i3status-rust-0.35.0/target/release/deps/libcharset-be0933ad4a2cb80a.rmeta --extern data_encoding=/var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/i3status-rust-0.35.0/target/release/deps/libdata_encoding-57c6dfb996cbf047.rmeta --extern quoted_printable=/var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/i3status-rust-0.35.0/target/release/deps/libquoted_printable-7ab693df8299fc7b.rmeta --cap-lints allow -C strip=none -C linker=x86_64-pc-linux-gnu-gcc -C target-feature=-crt-static -C link-arg=-Wl,-O1 -C link-arg=-Wl,--as-needed -C link-arg=-Wl,-z,pack-relative-relocs`
error[E0609]: no field `data` on type `spa_pod_builder`
  --> /var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/cargo_home/gentoo/libspa-0.8.0/src/pod/builder.rs:38:25
   |
38 |         (*this).builder.data = (*this).data.as_mut_ptr().cast::<c_void>();
   |                         ^^^^ unknown field
   |
   = note: available field is: `_address`

error[E0609]: no field `size` on type `spa_pod_builder`
  --> /var/tmp/portage/x11-misc/i3status-rust-0.35.0/work/cargo_home/gentoo/libspa-0.8.0/src/pod/builder.rs:39:25
   |
39 |         (*this).builder.size = (*this)
   |                         ^^^^ unknown field
   |
   = note: available field is: `_address`
```

[build.log.txt](https://github.com/user-attachments/files/25662149/build.log.txt)

**Comment by bim9262** [comment]
Are you able to build from master with llvm 22? My distro still is using llvm 21 so I haven't tested this out.

**Comment by bim9262** [comment]
I built llvm from source and see this issue too. The version in master works as it's using version 0.9 of the pipewire crate.
I'm working on creating a new release.

**Comment by bim9262** [comment]
A new release (0.36.0) has been created.
